TAG: 'Prediction_Ber'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 2
PRECISION: 16
EPOCHS: 20

N_WORKERS: 8

DATASET:
  VERSION: 'trainval'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

LIFT:
  GT_DEPTH: False

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: False
  HDMAP:
    ENABLED: False

INSTANCE_FLOW:
  ENABLED: True

PROBABILISTIC:
  ENABLED: True
  METHOD: 'BERNOULLI'

PLANNING:
  ENABLED: False

FUTURE_DISCOUNT: 0.95

OPTIMIZER:
  LR: 2e-4


PRETRAINED:
   LOAD_WEIGHTS: True
